
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENTERO = 9;
  public static final int POR = 5;
  public static final int EOF = 0;
  public static final int MAS = 6;
  public static final int ID = 10;
  public static final int IGUAL = 7;
  public static final int error = 1;
  public static final int R_MOSTRAR = 8;
  public static final int PARENTESIS_C = 3;
  public static final int PUNTOYCOMA = 4;
  public static final int PARENTESIS_A = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "PUNTOYCOMA",
  "POR",
  "MAS",
  "IGUAL",
  "R_MOSTRAR",
  "ENTERO",
  "ID"
  };
}

