
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENTERO = 2;
  public static final int POR = 3;
  public static final int MOSTRAR = 9;
  public static final int LLAVE_C = 8;
  public static final int EOF = 0;
  public static final int MAS = 4;
  public static final int IF = 10;
  public static final int LLAVE_A = 7;
  public static final int error = 1;
  public static final int PARENTESIS_C = 6;
  public static final int PUNTOYCOMA = 11;
  public static final int PARENTESIS_A = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "POR",
  "MAS",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "MOSTRAR",
  "IF",
  "PUNTOYCOMA"
  };
}

